### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by reallinfo** [kaelzhang/caviar#4]
Hi, i am a logo designer. I contribute to open source projects that do not have logo. I deisgned a logo for caviar. Please let me know what you think. 

![caviar](https://user-images.githubusercontent.com/36298335/56062374-d4d79b00-5d74-11e9-8e74-4bf6dd48fe27.jpg)

**Comment by kaelzhang** [comment]
Oh, what a nice logo? Is it free to use?

**Comment by reallinfo** [comment]
Yeah, of course free. If you don't have anything you want to edit, i can send a pr for your source files.

**Comment by kaelzhang** [comment]
Cool 😄

**Comment by reallinfo** [comment]
I sent a pr. https://github.com/kaelzhang/caviar/pull/6

Plase check it. Is there any problem?

**Comment by kaelzhang** [comment]
Merged. It is perfect 👍

**Comment by kaelzhang** [comment]
/close

Close for now, plz be free to reopen it if necessary~
